#include "BspDriver_GPIO.h"



/**
  * @brief  GPIO初始化
  * @param  无
  * @retval 无
  */
void APP_GPIOConfig(void)
{
  __HAL_RCC_GPIOA_CLK_ENABLE();                          /* GPIOA时钟使能 */
	__HAL_RCC_GPIOB_CLK_ENABLE();                          /* GPIOB时钟使能 */
  __HAL_RCC_GPIOF_CLK_ENABLE();                          /* GPIOB时钟使能 */
  
  /*SEG1 IO口初始化*/
  LL_GPIO_SetPinMode(SEG1_GPIO_PORT, SEG1_GPIO_PIN, LL_GPIO_MODE_OUTPUT);
  LL_GPIO_SetPinOutputType(SEG1_GPIO_PORT, SEG1_GPIO_PIN, LL_GPIO_OUTPUT_PUSHPULL);
  LL_GPIO_SetPinSpeed(SEG1_GPIO_PORT, SEG1_GPIO_PIN, LL_GPIO_SPEED_FREQ_HIGH);
  LL_GPIO_SetPinPull(SEG1_GPIO_PORT, SEG1_GPIO_PIN, LL_GPIO_PULL_NO);
  /*SEG2 IO口初始化*/
  LL_GPIO_SetPinMode(SEG2_GPIO_PORT, SEG2_GPIO_PIN, LL_GPIO_MODE_OUTPUT);
  LL_GPIO_SetPinOutputType(SEG2_GPIO_PORT, SEG2_GPIO_PIN, LL_GPIO_OUTPUT_PUSHPULL);
  LL_GPIO_SetPinSpeed(SEG2_GPIO_PORT, SEG2_GPIO_PIN, LL_GPIO_SPEED_FREQ_HIGH);
  LL_GPIO_SetPinPull(SEG2_GPIO_PORT, SEG2_GPIO_PIN, LL_GPIO_PULL_NO);  
  /*SEG3 IO口初始化*/
  LL_GPIO_SetPinMode(SEG3_GPIO_PORT, SEG3_GPIO_PIN, LL_GPIO_MODE_OUTPUT);
  LL_GPIO_SetPinOutputType(SEG3_GPIO_PORT, SEG3_GPIO_PIN, LL_GPIO_OUTPUT_PUSHPULL);
  LL_GPIO_SetPinSpeed(SEG3_GPIO_PORT, SEG3_GPIO_PIN, LL_GPIO_SPEED_FREQ_HIGH);
  LL_GPIO_SetPinPull(SEG3_GPIO_PORT, SEG3_GPIO_PIN, LL_GPIO_PULL_NO); 
  /*SEG4 IO口初始化*/
  LL_GPIO_SetPinMode(SEG4_GPIO_PORT, SEG4_GPIO_PIN, LL_GPIO_MODE_OUTPUT);
  LL_GPIO_SetPinOutputType(SEG4_GPIO_PORT, SEG4_GPIO_PIN, LL_GPIO_OUTPUT_PUSHPULL);
  LL_GPIO_SetPinSpeed(SEG4_GPIO_PORT, SEG4_GPIO_PIN, LL_GPIO_SPEED_FREQ_HIGH);
  LL_GPIO_SetPinPull(SEG4_GPIO_PORT, SEG4_GPIO_PIN, LL_GPIO_PULL_NO);   
  /*SEG5 IO口初始化*/
  LL_GPIO_SetPinMode(SEG5_GPIO_PORT, SEG5_GPIO_PIN, LL_GPIO_MODE_OUTPUT);
  LL_GPIO_SetPinOutputType(SEG5_GPIO_PORT, SEG5_GPIO_PIN, LL_GPIO_OUTPUT_PUSHPULL);
  LL_GPIO_SetPinSpeed(SEG5_GPIO_PORT, SEG5_GPIO_PIN, LL_GPIO_SPEED_FREQ_HIGH);
  LL_GPIO_SetPinPull(SEG5_GPIO_PORT, SEG5_GPIO_PIN, LL_GPIO_PULL_NO);    
  /*SEG6 IO口初始化*/
  LL_GPIO_SetPinMode(SEG6_GPIO_PORT, SEG6_GPIO_PIN, LL_GPIO_MODE_OUTPUT);
  LL_GPIO_SetPinOutputType(SEG6_GPIO_PORT, SEG6_GPIO_PIN, LL_GPIO_OUTPUT_PUSHPULL);
  LL_GPIO_SetPinSpeed(SEG6_GPIO_PORT, SEG6_GPIO_PIN, LL_GPIO_SPEED_FREQ_HIGH);
  LL_GPIO_SetPinPull(SEG6_GPIO_PORT, SEG6_GPIO_PIN, LL_GPIO_PULL_NO);
  /*声音传感器 IO口初始化*/
  LL_GPIO_SetPinMode(MIC_GPIO_PORT, MIC_GPIO_PIN, LL_GPIO_MODE_INPUT);
  LL_GPIO_SetPinSpeed(MIC_GPIO_PORT, MIC_GPIO_PIN, LL_GPIO_SPEED_FREQ_HIGH);
  LL_GPIO_SetPinPull(MIC_GPIO_PORT, MIC_GPIO_PIN, LL_GPIO_PULL_NO); 
  
}


